source "https://rubygems.org"

gem "rails"
gem "pg"
gem "puma"

gem "bootsnap"

group :development, :test, :test_data do
  gem "test_data", path: ".."
  gem "standard"
  gem "pry-rails"
  gem "factory_bot_rails", require: false
  gem "noncommittal"
  gem "rspec-rails"
end

group :test do
  gem "capybara", ">= 3.26"
  gem "selenium-webdriver"
  gem "webdrivers"
end
