#!/usr/bin/env bash

PS4='[script/test:${LINENO}] $ '
set -euo pipefail
set -x

cd example

# Reset database:
bin/rake db:drop
dropdb example_test_data 2>/dev/null || true

# Reset files:
git checkout app/models/boop.rb
git checkout config/application.rb
git checkout config/database.yml
git checkout db/schema.rb
git clean -xdf .
